### ISSUE TITLE
Try to use reflection to newer versions of Bukkit

### ISSUE THREAD

**Issue by zubiden** [prettydude/F3Name#6]
This could add support for 1.14+ versions.

**Comment by TuxCoding** [comment]
In Bukkit we could use ProtocolLib for that. Would you accept a pull request for it?

**Comment by zubiden** [comment]
I did not expect anyone to notice my development notes (maybe I need to choose a different place for them 😅).
This plugin does not require any dependencies, because I directly interact with NMS. (that's faster)
I made a hotfix because I forgot to replace one method, so plugin stopped working without Bungee version, and added ReflectionPayloadPacket. It needs to work until the plugin updates to the new version.

**Comment by zubiden** [comment]
Added in 2.2
